### ISSUE TITLE
List functionalities of godwoken

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/shaping#9]
- [x] Txn List: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008242725
- [x] Tx Info: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008242759
---
- [x] Transfer between Layer1 and Layer2: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1013878010
- [x] Block List: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008243431
- [x] Block Info: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008243966
- [x] Account Info: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008246524
- [x] Diff and switch between mainnet and testnet

---
- [x] Pending Tx List: Add pending tx list once mempool in the read-only node is ready

---
- [x] Top Account List(Holder list): https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008248404
- [x] Token Info: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008248039

---
- [x] Verified Contract List: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008252563
- [x] Contract Info: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008252279
- [x] Charts: https://github.com/nervina-labs/ckb-wallet-and-explorer/issues/9#issuecomment-1008268442

---
- [ ] <del>Forked Block List</del>
- [ ] <del>Uncle Block List</del>
- [ ] <del>Internal Tx List: https://github.com/Magickbase/ckb-wallet-and-explorer/issues/9#issuecomment-1108009879</del> hold on for https://github.com/Magickbase/ckb-wallet-and-explorer/issues/9#issuecomment-1109551860
- [x] Events: https://github.com/Magickbase/ckb-wallet-and-explorer/issues/9#issuecomment-1108058513
- [x] Token List
- [x] Stats: https://github.com/Magickbase/ckb-wallet-and-explorer/issues/9#issuecomment-1008268442

**Comment by Keith-CY** [comment]
### Internal Txn List

- [ ] Parent Txn Hash: transaction hash including this internal txn;
- [ ] Block: block number and hash including the parent txn;
- [ ] Age: timestamp of the block;
- [ ] From: from address of this internal txn;
- [ ] From Alias: alias of the from address, e.g. registered contract name;
- [ ] To: to address of this internal txn;
- [ ] To Alias: alias of the to address, e.g. registered contract name;
- [ ] value: transferred ckb value.

**Comment by Keith-CY** [comment]
### Events(Logs)

In contract page(https://etherscan.io/address/0x2ed6c4b5da6378c7897ac67ba9e43102feb694ee#events)

- [ ] tx hash: transaction triggers this event
- [ ] method: method id
- [ ] ABI
- [ ] logs: Raw log data

**Comment by zmcNotafraid** [comment]
> ### Internal Txn List
> In contract page(https://etherscan.io/address/0x2ed6c4b5da6378c7897ac67ba9e43102feb694ee#internaltx)
> 
> * [ ]  Parent Txn Hash: transaction hash including this internal txn;
> * [ ]  Block: block number and hash including the parent txn;
> * [ ]  Age: timestamp of the block;
> * [ ]  From: from address of this internal txn;
> * [ ]  From Alias: alias of the from address, e.g. registered contract name;
> * [ ]  To: to address of this internal txn;
> * [ ]  To Alias: alias of the to address, e.g. registered contract name;
> * [ ]  Value: transferred ckb value.
> 
> In transaction page(https://etherscan.io/tx/0x9d159197480a7f4b77043566020ab31e81f6f2ab9ae80fa75896a3816449309b#internal), since internal txns wouldn't be too many in one txn, all records can be returned together.
> 
> * [ ]  From: from address of this internal txn;
> * [ ]  From Alias: alias of the from address;
> * [ ]  To: to address of this internal txn;
> * [ ]  To Alias: alias of the to address;
> * [ ]  Value: transferred ckb value.
> * [ ]  Caller: the contract address triggered this internal txn;
> * [ ]  Caller Alias: alias of the caller

Internal Transaction seems to be hard to implement.From this: https://ethereum.stackexchange.com/questions/3417/how-to-get-contract-internal-transactions.
And I read the Blockscout code. They get internal transaction from parity or geth, these third rpc service.
So this function need delay
